### ISSUE TITLE
채팅방 만료(채팅 참가자 삭제 포함) 이벤트 수신 핸들러 추가

### ISSUE THREAD

**Issue by coke98** [Re-4aliens/backend#136]
## 📄 이슈 목적

- 매칭에서 만들어둔 이벤트를 채팅 도메인에서 수신할 수신 핸들러 만들기

## ✅ 체크 리스트
- [ ] 이전의 모든 채팅방을 닫는 chatRoom expire 이벤트 수신자 생성
- [ ] 모든 chatParticiant 삭제

## ➕참고 자료
- 

## ⌛ 예상 소요 시간
-

**Comment by suhyun0918** [comment]
제가 만들어 놓고는 깜빡하고 이벤트 수신 코드를 작성해달라고 말씀을 못드렸네요 ! :(

뒤늦게 업무 부담을 드리게되어 죄송합니다! ㅠㅠ
