### ISSUE TITLE
채팅 도메인 구현

### ISSUE THREAD

**Issue by coke98** [Re-4aliens/backend#36]
## 📄 이슈 목적

- 웹소켓(Stomp)를 활용하여 채팅 기능을 구현합니다.

## ✅ 체크 리스트
- [x] 채팅방 메시지 조회
- [x] 채팅방 요약 정보 조회
- [x] 메시지 전송
- [x] 메시지 읽음 처리
- [x] 웹소켓 연결 종료

## ➕참고 자료
- 채팅 기능 설계
https://www.notion.so/FriendShip-cffe85a2383f42b9865468462288056a?pvs=4
- 웹소켓 채팅 전송시 권한 확인 방법https://www.notion.so/cb879fe56f0d4a76883bc294cad61bdc?pvs=4

## ⌛ 예상 소요 시간
- 48H

**Comment by coke98** [comment]
@mjj111 @Oniqued 
기존에 도메인 네이밍을 Chatting으로 정했었는데요
"Chat"으로 변경하는 것은 어떨까합니다

1. 명확성
Chatting(채팅을 하고 있는)이라는 네이밍은 채팅을 하는 행위에만 집중적인 표현으로 느껴집니다.
Chat자체에도 명사, 동사형 의미가 둘다 있는데, Signing up, Applicationing 같이 불필요한 ing를 사용하고 있다고 생각이 들었어요.
한국에서는 채팅이라는 네이밍으로 굳혀져 있지만, 구현 자료를 조사하면서도, 실제 구글 검색 결과를 보더라도
chat app: 7,510,000,000개, chatting app: 291,000,000개로 사용량이 25배 이상 차이날 정도로 채팅 도메인에 대해서는
Chat을 사용하는 것이 일반적이고 자연스럽다고 생각이 들었습니다.
채팅뿐 아니라, 부수적인 차단, 신고 기능까지 다루기 위해서는 
도메인 이름을 chatting -> chat 으로 포괄적인 의미를 두는게 더 좋을것 같다는게 의견입니당

2. 가독성
ChattingService -> ChatService
ChattingClient -> ChatClient
chatting/message/send -> chat/message/send
등 조금 더 짧아진 네이밍도 이점이 있겠네용

**Comment by mjj111** [comment]
확인했습니다 위와같이 명확성과 가독성에 이점을 얻을 수 있다면 Chat으로 네이밍 변경이 더 좋아보이네요! 🙆‍♂️
